### ISSUE TITLE
Appending the kernel

### ISSUE THREAD

**Issue by Wellington-Froelich** [BradyAJohnston/BNotebooks#6]
Hi, I am trying to add on BNotebook (v0.0.5) to blender (v 4.0.2), but I am getting somethings different than what the installation for BNotebook guide says. 
The first thing is that: it says jupyterlab 4.0.7 is installed as opposed to ipykernel version # is installed
The second thing is that: it says reinstall jupyterlab as opposed to ipykernel
The third thing is that when I click Append Kernel I get the following error message: 

```
Python: Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 4.0\4.0\python\lib\subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Program Files\Blender Foundation\Blender 4.0\4.0\python\lib\subprocess.py", line 1456, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified
```

I know that my environment variables are properly set up. So I am assuming it's an issue with BNotebook or Blender. One more thing I will note is that my jupyter labs version that I have installed is 4.0.11 not 4.0.7 as it says in Blender. Any ideas on how to solve this issue? I have tried the same thing with Blender version 3.6 to no avail. I have also tried previous versions of BNotebook to no avail.

**Comment by BradyAJohnston** [comment]
Hi there, are you able to provide more information about what you system is? It seems windows, but which OS?

The idea behind BNotebooks is that Blender (and the python bundled inside of Blender) becomes it's own Python environment, so having Jupyter Labs installed elsewhere _in theory_ shouldn't affect it.

Are you able to provide a screenshot of the addon preferences, where the append & install button are?

**Comment by Wellington-Froelich** [comment]
Hi Brady thanks for getting back so quickly! Sure here is a screenshot. And correct, the system is Windows 10 Pro. My Python version that I have installed (not sure if that matters either) is python311

![image](https://github.com/BradyAJohnston/BNotebooks/assets/36109279/15544671-1e24-4cfb-85bb-9efdcb9e0b57)

**Comment by Wellington-Froelich** [comment]
The installation location of Jupyter on my PC is the standard location (from what I can tell) C:\Users\YourUsername\AppData\Local\Programs\Python\Python311\Scripts and there I have all the jupyter executables 
![image](https://github.com/BradyAJohnston/BNotebooks/assets/36109279/0bb3e2af-6412-43a8-b876-e4965724def3) 

Did you somehow install Jupyter into a file path in the Blender download? For example somewhere in here: 
![image](https://github.com/BradyAJohnston/BNotebooks/assets/36109279/cbcd6c36-f077-41c5-b3b7-c9a068e950fc)

**Comment by Wellington-Froelich** [comment]
I've dug a little deeper. The error message I have now (Blender version 3.6, BNotebook v0.0.5) is this: 
```
Python: Traceback (most recent call last):
  File "C:\Users\BenjaminWorkinger\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\BNotebooks\pref.py", line 80, in execute
    installer.install(
  File "C:\Users\BenjaminWorkinger\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\BNotebooks\installer.py", line 80, in install
  File "C:\Users\BenjaminWorkinger\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\BNotebooks\installer.py", line 47, in get_kernel_path
  File "C:\Program Files\Blender Foundation\Blender 3.6\3.6\python\lib\subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Program Files\Blender Foundation\Blender 3.6\3.6\python\lib\subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Program Files\Blender Foundation\Blender 3.6\3.6\python\lib\subprocess.py", line 1456, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified
```
The lines in question in this error message are these ones: 
```
  File "C:\Users\BenjaminWorkinger\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\BNotebooks\installer.py", line 80, in install
  File "C:\Users\BenjaminWorkinger\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\BNotebooks\installer.py", line 47, in get_kernel_path
```
because that file does not exist in my directory and it's not a hidden item. Any thoughts?

**Comment by wstho** [comment]
getting the same error message as above in MacOS14.3 with Blender 4.02. The path to Blender's Jupyter installation seems to have changed. Have tried manually overriding in the installer.py script, but no luck yet.
